name: Vue Storefront Pull Request
description: Vue Storefront Pull Request
inputs:
  test_command:
    description: Tests Running Command
    default: 'yarn test --coverage --passWithNoTests --forceExit'
    required: true
  test_disabled:
    description: Tests and Coverage Check Will Be Disabled
    default: 'false'
    required: false
  test_failed:
    description: Action Failing Below this Coverage Percentage Value
    default: '90'
    required: false
  test_report:
    description: Add Report Comment to Related Pull Request
    default: 'true'
    required: false
  test_report_comment_id:
    description: Add Report to the Selected Comment of the Related Pull Request
    default: 'false'
    required: false
  lighthouse_urls:
    description: Lighthouse URL's (separated with ",")
    default: 'http://localhost:4000'
    required: true
  lighthouse_report:
    description: Add Lighthouse Report Comment to Related Pull Request
    default: 'true'
    required: false
  lighthouse_report_comment_id:
    description: Add Report to the Selected Comment of the Related Pull Request
    default: 'false'
    required: false
  github_token:
    description: Github Token
    default: ''
    required: false
runs:
  using: node12
  main: lib/index.cjs.js
